version: '3.8'

services:
  web:
    build: ./thoughts_app_service
    env_file:
      - ./thoughts_app_service/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    environment:
      RUNNING_IN_DOCKER: "True"

  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus
    restart: 'no'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  postgres_data: {}
  prometheus_data: {}
  grafana_data: {}
  mongodb_data: {}
