global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/prometheus-vYMm9vGuT0/metrics'
    static_configs:
      - targets: ['web:8000']