# Generated by Django 5.0.3 on 2024-03-28 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_file_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeditationNarrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audio_file_name', models.CharField(max_length=255)),
                ('cover_file_name', models.CharField(max_length=255)),
                ('meditation_narrator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thoughts_core.meditationnarrator')),
                ('meditation_theme_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thoughts_core.meditationtheme')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('achievements', models.ManyToManyField(blank=True, to='thoughts_core.achievement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start_time', models.DateTimeField(auto_now_add=True)),
                ('end_session', models.DateTimeField(null=True)),
                ('meditation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts_core.meditation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts_core.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MeditationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('meditation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts_core.meditation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts_core.userinfo')),
            ],
        ),
    ]
